### ISSUE TITLE
What does it should be when we call `toArray()`?

### ISSUE THREAD

**Issue by RaulWei** [ecrmnn/collect.js#107]
Suppose there is an object collection like that
```
people = {
  name: 'wei',
  sex: 'male',
  phone: [15211111111, 13511111111],
  company: {
    name: 'IBM',
    city: 'BJ'
  }
}
```
What does it should be if we call `collect(people).toArray()`?
In current implementation, it will return
`[ 'wei', 'male', [ 15211111111, 13511111111 ], { name: 'IBM', city: 'BJ' } ]`.
Should it be `[ 'wei', 'male', [ 15211111111, 13511111111 ], [ 'IBM', 'BJ' ] ]`?

**Comment by g-plane** [comment]
I think `[ 'wei', 'male', [ 15211111111, 13511111111 ], [ 'IBM', 'BJ' ] ]` is not consistent with Laravel.
For example (in Laravel 5.4):
```php
$collect = collect([
        'name' => 'wei',
        'sex' => 'male',
        'phone' => [15211111111, 13511111111],
        'company' => ['name' => 'IBM', 'city' => 'BJ']
    ]);

return dd($collect->toArray());
```

The result is:
![image](https://user-images.githubusercontent.com/17216317/27392018-1010d9e8-56d8-11e7-8b15-24914e63c08c.png)

**Comment by ecrmnn** [comment]
It's not consistent with Laravel right now because in PHP have associative arrays, while JS don't.

I think it would be weird to return an object from a method called ``toArray()``, but it would be consistent with Laravel.

What do you think? I'm open for a discussion

**Comment by solomonhawk** [comment]
It is my(random JS developer) opinion that the closest equivalent data structure in JS would be a nested array of `[key, value]` pairs. This is admittedly more awkward to work with than an object or real associative array. I wonder what the use case is for calling `toArray()` on an object wrapped in `collect`.

Input:
```js
people = {
  name: 'wei',
  sex: 'male',
  phone: [15211111111, 13511111111],
  company: {
    name: 'IBM',
    city: 'BJ'
  }
}
```

Output:
```js
[
  ['name', 'wei'],
  ['sex', 'male'],
  ['phone', [15211111111, 13511111111]],
  ['company', { name: 'IBM', city: 'BJ' }]
]
```

**Comment by wmj0cn** [comment]
dont see the usefulness of this method, would you like to give a real use scenario of it?

**Comment by faalotaiby** [comment]
In my opinion calling it ToArray is not useful,   unless you needed an array, that says pass it to method which only accepted Integer() as a parameter.

**Comment by RaulWei** [comment]
Sorry for that I'm not familiar with Laravel, I propose this problem standing at the general position.
