### ISSUE TITLE
Sum using iterator/reduce

### ISSUE THREAD

**Issue by tenghuanhe** [ecrmnn/collect.js#118]
I've opened [ PR#95](https://github.com/ecrmnn/collect.js/pull/95) several days ago, which uses `reduce` instead of `iterator` to implement `sum` function with fewer lines of code. However, [a simple benchmark test](https://github.com/tenghuanhe/collectjs-sum-benchmark) shows `iterator_sum` is 3x ~ 5x times faster than `reduce_sum`.

According to https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce, `reduce` does have extra overhead compared to directly using `iterator`.

So the change of [ PR#95](https://github.com/ecrmnn/collect.js/pull/95) may be revoked and using origin `sum` implementation is better. Using `reduce` makes the code shorter, it harms efficiency. How do you think about it? @ecrmnn

**Comment by ecrmnn** [comment]
Thanks for benchmarking and figuring this out @tenghuanhe. Implemented the old method now.
