### ISSUE TITLE
mapWithKeys after groupBy errors with "this.items.forEach is not a function"

### ISSUE THREAD

**Issue by Helfull** [ecrmnn/collect.js#119]
hey,

i have this pipeline

```js
const stats = collect(this.content)
                    .filter(value => {
                        return collect([
                            'created', 'updated', 'deleted'
                        ]).contains(value.description);
                    })
                    .groupBy(value => value.description)
                    .mapWithKeys(value => {
                        return [value.description, collect(value.all()).count()];
                    });
```

and this does error with `this.items.forEach is not a function` at the `mapWithKeys` method,

is it intentional that `mapWithKeys` does not support hashmaps?

**Comment by ecrmnn** [comment]
Could you provide the ``this.content``?

**Comment by Helfull** [comment]
Something like this

```
[
  {
    "id": 5,
    "log_name": "default",
    "description": "created",
  },
  {
    "id": 6265,
    "log_name": "default",
    "description": "updated",
  },
  {
    "id": 6268,
    "log_name": "default",
    "description": "deleted",
  },
  {
    "id": 999,
    "log_name": "default",
    "description": "FOOBAR STUFF",
  },
  {
    "id": 123456,
    "log_name": "default",
    "description": "deleted",
  }
]
```

**Comment by ecrmnn** [comment]
Ah, yeah. Hashmaps/objects are not supported. I tried to solve this in a different way but didn't find anything that worked the way I wanted. I'll dig into this. Maybe I'll rewrite several methods. This should be possible.

**Comment by Helfull** [comment]
hey wouldn't it be easy to just rework the `each` method and then use this in place for the build in `forEach`?

**Comment by ecrmnn** [comment]
Yep, something like that. I also want to make ``map`` and ``transform`` work with objects.

**Comment by Helfull** [comment]
if i find time this weekend i could see if i can make a PR

**Comment by ecrmnn** [comment]
Thanks for you PR @Helfull 😄
