### ISSUE TITLE
Doesn't work with vuejs v-for

### ISSUE THREAD

**Issue by santigarcor** [ecrmnn/collect.js#125]
First thanks for this package, it's like using laravel collections.

I tried to use one of your collections in a v-for in vue and it doesn't iterate over the collection items, instead it iterates over the collection Object properties.

I have the latest version of your package.

**Comment by ecrmnn** [comment]
Hi

Yes, a normal ``for in ...`` have that behaviour. It's possible to iterate through ``Collection`` using ``for of ...`` but I don't know if that's possible in ``v-for``. I'll check it out.

In the meanwhile I'd recommend something like this:
```html
<ul>
    <li v-for="post in posts.all()">
        {{ post.title }}
    </li>
</ul>
```

**Comment by santigarcor** [comment]
Ok thanks!

**Comment by tlgreg** [comment]
Currently vue supports only actual arrays with v-for.
Most likely iterator support will only come in vue3, though the [issue](https://github.com/vuejs/vue/issues/5893) is still open.

**Comment by ecrmnn** [comment]
Ah. Thanks for clearing that up, @tlgreg. I tweeted Evan You about it but havn't got an answer yet.

**Comment by alfredocodekit** [comment]
`<li class="b-task" v-for="task in sortedTasks" @click="completeTask(task)">`
`          computed: {
            sortedTasks: function() {
              return collect(this.tasks).sortBy('title').toArray()
            }
          },`
