### ISSUE TITLE
bug in merge&union method?

### ISSUE THREAD

**Issue by Zion-007** [ecrmnn/collect.js#126]
`const collection = collect({
  a: 'A',
  b: 'B',
  d: 'D'
});

const merged = collection.merge({
  a: 'AAA',
  b: 'BBB',
  c: 'CCC'
});

console.log(merged.all()) // { a: 'AAA', b: 'BBB', c: 'CCC' } but expect  { a: 'AAA', b: 'BBB', c: 'CCC' , d: 'D'}

console.log(merged.all().b) // BBB
merged.forget('b')
console.log(merged.all().b) // B, expect undefined
`
i know in method file: merge.js and union.js use `var collection = Object.create(this.items)`, does use `clone` like is right/better?

env: node -v v6.10.2

**Comment by ecrmnn** [comment]
Wow thanks. Nice find. Fixed in 3.0.47
