### ISSUE TITLE
Adding dump command?

### ISSUE THREAD

**Issue by mikeerickson** [ecrmnn/collect.js#129]
In light of the pending Laravel 5.5 release, so you have any plans for add `dump` and/or `dd` commands?

**Comment by martinandersen3d** [comment]
Suggestions:
Set a debug flag in Collect, so eatch step of the chain is dumped to console..?

Could also be in indexed order.

**Comment by Helfull** [comment]
i will take over this

expect to see a pull request tomorrow

**Comment by ecrmnn** [comment]
Thanks for reporting.

Added
- concat
- crossJoin
- dd
- dump
- intersectByKeys
- macro
- mapInto
- mapToGroups
- unless
- unwrap
- wrap

This is fixed in the latest release, ``3.0.50``
