### ISSUE TITLE
except on arrays

### ISSUE THREAD

**Issue by martinandersen3d** [ecrmnn/collect.js#131]
Problem:
except doesn't work on arrays, but intersect does? Is this inconsistent or correct behavior?

const testE = collect([1,2,3,4,5]).except([2,12]).all()
// result is an object: ​​​​​{ '0': 1, '1': 2, '2': 3, '3': 4, '4': 5 }​​​​​
// think i wanted array: [12]

const testI = collect([1, 2, 3, 4, 5]).intersect([1, 2, 3, 9]).all();
// result: [1,2,3] 

except returns object, intersect returns array.

in sql world:
http://www.essentialsql.com/wp-content/uploads/2014/10/UnionInsersectExcept.jpg

thanks :-)

Ps. Love this awesome framework ;-)

**Comment by ecrmnn** [comment]
Thanks for reporting.

This is fixed in the latest release, ``3.0.50``

**Comment by Gi972** [comment]
Hello,

Except return always a object, do you fix it?
