### ISSUE TITLE
FlatMap functionality is not as expected

### ISSUE THREAD

**Issue by JCWolf** [ecrmnn/collect.js#137]
The `flatMap` method doesn't work as expected for a collection (an array of objects).
For example, if I have a list of employees and each employee has a list of customers and I want to get a list of all customer I would use flatMap as the below:
**Input:**
```javascript
let employees = collect([
  {
    customers :[
      {
        name : "c1"
      },
      {
        name : "c2"
      }
    ]
  },
  {
    customers :[
      {
        name : "c3"
      }
    ]
  }
])

let customers = employees.flatMap(employee => employee.customers)
```
**Expected result:**
```javascript
[
  {
    name : "c1"
  },
  {
    name : "c2"
  },
  {
    name : "c3"
  }
]
```
**Actual result:**
_Error: Cannot read property '0' of undefined(in the collect.js flatMap source code)_

Laravel's [flatMap source code](https://github.com/illuminate/support/blob/master/Collection.php#L919)

Is there a good reason why flatMap behaves like that? If it is an issue with this can you, please, implement the correct version for flatMap?

Thank you!

**Comment by ecrmnn** [comment]
Hi @JCWolf 

I actually discovered and fixed this here the other day, I just didn't have the time to merge and push it.

I'll push a new version some time today 👍

**Comment by JCWolf** [comment]
Nice. Paste a link, please, for the merge here so I get notified.
Thanks!
