### ISSUE TITLE
Only, Union on arrays.. is the result correct?

### ISSUE THREAD

**Issue by martinandersen3d** [ecrmnn/collect.js#144]
Only:
collect([1, 2, 3, 4, 5]).only([2, 3,12]).all();

// => [ 2 ]

is this correct? or should it output [2,3]? 
as i understand, only is the inverse of Expect. 

-------------------------
union:
collect([1, 2, 3, 4, 5]).union([2, 3, 4,12]).all() 
// =>[ 1, 2, 3, 4, 5 ]

union is supposed to merge them all together?
please see:
[http://www.essentialsql.com/wp-content/uploads/2014/10/UnionInsersectExcept.jpg](http://www.essentialsql.com/wp-content/uploads/2014/10/UnionInsersectExcept.jpg)

**Comment by ecrmnn** [comment]
Hi @martinandersen3d 

Thanks for reporting.

You're correct about the ``only`` method. This is fixed in the 4.0.0. release. Just published.

``union`` works this way in Laravel Collections, so it will stay like this 👍
