### ISSUE TITLE
The only() method with array It does not work properly

### ISSUE THREAD

**Issue by jay7793** [ecrmnn/collect.js#147]
```
const collection = collect([{
  name: 'JavaScript: The Good Parts', pages: 176
}, {
  name: 'JavaScript: The Definitive Guide', pages: 1096
}]);

return collection.only('name').all()
```

I'm trying to find a 'name' property from the collection. It does not work properly. It displays empty arrays [] I want to know my approach is correct or not.

Thank you.

**Comment by ecrmnn** [comment]
Hi @jay7793 

It is working correctly, but I think you're looking for the ``[pluck](https://github.com/ecrmnn/collect.js#pluck)`` method.

```js
const collection = collect([{
  name: 'JavaScript: The Good Parts', pages: 176
}, {
  name: 'JavaScript: The Definitive Guide', pages: 1096
}]);

collection.pluck('name').all();

//=> [
//=>    'JavaScript: The Good Parts',
//=>    'JavaScript: The Definitive Guide' ,
//=> ]
```

**Comment by jay7793** [comment]
Hi @ecrmnn 

Thank you so much for the suggestions and examples. Again, can you show how only() method it works with an array of objects? I think the above code is correct. But why not work?

**Comment by Helfull** [comment]
@jay7793 `only` does support hashmaps but not collections of objects.
this is the same behavior as in laravel 5.5 which uses the `array_intersect_key` method from php

https://github.com/ecrmnn/collect.js#only
https://laravel.com/docs/5.5/collections#method-only
http://php.net/manual/en/function.array-intersect-key.php

**Comment by jay7793** [comment]
@Helfull 

Thank a lot for the suggestions.

**Comment by ecrmnn** [comment]
Thanks for your reply @Helfull, that's correct.

@jay7793; This is actually something that has bothered me too, almost to the point of making a PR to change the Laravel implementation.

A way of removing or adding keys from a collection with an array of objects is with ``map`` and ``transform``, like this:

```js
const collection = collect([{
  name: 'JavaScript: The Good Parts', pages: 176
}, {
  name: 'JavaScript: The Definitive Guide', pages: 1096
}]);

collection.transform((item) => {
  delete item.pages;

  return item;
});
```
