### ISSUE TITLE
Splitting functions into separate files

### ISSUE THREAD

**Issue by BrainMaestro** [ecrmnn/collect.js#15]
Due to the number of implemented functions, the code starts getting a little difficult to parse. Would you be interested in splitting the functions into separate files? It's not necessary, but I feel like it would help encourage contribution.

Great project btw.

**Comment by sacharbit** [comment]
It seems pretty weird to split the document into multiple separate files since it's a collection of functions and methods. Which functions would go with which? Also, it's nice to have only one file to implement it if we don't want to use npm.

**Comment by BrainMaestro** [comment]
Not weird at all. Take a look at [ramda](https://github.com/ramda/ramda/tree/master/src). Also why would you not use a package manager? I don't think maintainers should care about that scenario.

**Comment by mikebronner** [comment]
Perhaps a compromise would be to sort the methods alphabetically?

**Comment by ecrmnn** [comment]
Great idea @BrainMaestro! I would like to do that with the tests as well.
Feel free to submit PR 😃

**Comment by ecrmnn** [comment]
PS: Closed because I want to keep open issues to a minimum

**Comment by mikeerickson** [comment]
@ecrmnn Since @mikebronner does not know how to do testing might be out of scope.  But the request indeed a good one.   I am about to jump in with both feet and get my hands dirty.

**Comment by mikebronner** [comment]
@mikeerickson This is @BrainMaestro 's inquiry. :)

**Comment by mikeerickson** [comment]
@BrainMaestro whoops, sorry see above :-)

cc: @mikebronner
