### ISSUE TITLE
Sorting strings with accented characters

### ISSUE THREAD

**Issue by douglaszaltron** [ecrmnn/collect.js#153]
Knows how to order an array with words with special characters like accents?

Javascript has a native method sort that allows sorting ( array.sort() ). Also you can provide your own custom sorting function. Are two ways to overcome this behavior localeCompare and Intl.Collator provided. in .sortBy() could have this option.
 
collect(array).sortBy('name');

returns 'Albacete' before 'Álava', and I want 'Álava' before 'Albacete'. =(

Thanks a lot, @ecrmnn

**Comment by ecrmnn** [comment]
Using ``macro()`` you can build this into ``collect.js``

> Note that I'm *not* using a shorthand function when defining a macro. This will give you the wrong scope, and ``this`` will be `˙undefined``.

```js
'use strict';

const collect = require('collect.js');

const collection = collect([{ name: 'Amana' }, { name: 'Albacete' }, { name: 'Álava' }]);

collect().macro('intlCollator', function intlCollator(lang, key) {
  return this.sort((a, b) => new Intl.Collator(lang).compare(a[key], b[key]));
});

collection.intlCollator('br', 'name').dump();
```

**Comment by ecrmnn** [comment]
Closed due to inactivity. Comment or open a new issue if you need further assistance :)

**Comment by douglaszaltron** [comment]
Tks! This works well ;)
