### ISSUE TITLE
count() does not work with hashmaps

### ISSUE THREAD

**Issue by Helfull** [ecrmnn/collect.js#154]
hey,

counting objects in a hashmap returns undefined

```
collect({}).count() // undefined
collect({foo:'bar'}).count() // undefined
```

might just be a version problem here

**Comment by ecrmnn** [comment]
That should have been fixed in 4.x. What version are you using?

**Comment by Helfull** [comment]
did try it after i updated to the newest version and works, the error was infront of the PC :D
