### ISSUE TITLE
where(' ' ,'like', ' ') like operator

### ISSUE THREAD

**Issue by mostafa6765** [ecrmnn/collect.js#157]
This is awesome collection as like laravel . 
like operator is very important as query system.
`.where('name','like','s%')`
another is 
`.orWhere()`
```php
.where('votes', '>', 100)
.orWhere('name', 'John')
```
`andWhere()` array condition

```php
$users = DB::table('users')->where([
    ['status', '=', '1'],
    ['subscribed', '<>', '1'],
])->get();
```

without those can't feel happiness .please add those collections.  @ecrmnn ❤️

**Comment by Helfull** [comment]
hey,

those methods are for the Eloquent Query builder not for collections in laravel. If i am not mistaken

**Comment by mostafa6765** [comment]
Right, I know. but if add those methods as collections that will be very helpful @Helfull

**Comment by ecrmnn** [comment]
Hi, @mostafa6765.

Glad you like the library.

As @Helfull says; those methods are not in Laravel Collection, but in the Eloquent query builder.
You may add them to your own instance of Collect.js by using ``macro()``.

Thanks for the suggestions, but this won't be implemented.
