### ISSUE TITLE
how to use it in plain javascript ?

### ISSUE THREAD

**Issue by dhsont** [ecrmnn/collect.js#158]
Hi i want to use this library in plain javascript like we use Jquery.

this is very good library and i want to use this in my html file.
please guide how to use this.

**Comment by ecrmnn** [comment]
Hi, @dhsont 

You can download the [collect.js.min](https://raw.githubusercontent.com/ecrmnn/collect.js/master/build/collect.min.js)

And add it with a normal ``<script>`` tag.

**Comment by dhsont** [comment]
Thank you very much @ecrmnn ,

Lib is working like charm.

Library  is missing findByIndex method.

ex

**Comment by ecrmnn** [comment]
Glad you like it. Cheers!
