### ISSUE TITLE
ReferenceError: collect is not defined

### ISSUE THREAD

**Issue by sreejith2base** [ecrmnn/collect.js#159]
Hi 

I am using Laravel 5.5;

I have installed using npm 

`npm install --save collect.js`
 
and added the following on **bootstrap.js**

`window.collect = require('collect.js')`

and run 
`npm run dev`

inside my blade blade file i have added

```
<script>
collect([1, 2, 3]).all();
</script>
```

But I am getting an error

ReferenceError: collect is not defined

**Comment by ecrmnn** [comment]
Could you try ``global.collect = require('collect.js')``

**Comment by sreejith2base** [comment]
Done, It is working now. 
Thanks @ecrmnn

**Comment by jagoanmamah** [comment]
i have same problem, still not worked
