### ISSUE TITLE
How to access value by index ID in array ?

### ISSUE THREAD

**Issue by dhsont** [ecrmnn/collect.js#160]
*Library  is missing Value By Index Functionality

ex    
~~~
myArray = collect([1,4,5,9,9,5,1,1,5,4,1,7,1,0,9,3,7,4,8,9,3,6,3,3]);

val = myArray[3];
~~~

it is not returning value .

it should return value **9**

**Comment by ecrmnn** [comment]
This could be better documented. 

``myArray.get(index)``

**Comment by ecrmnn** [comment]
[This is documented in 4.0.12](https://github.com/ecrmnn/collect.js#get)
