### ISSUE TITLE
Can be used in nested objects?

### ISSUE THREAD

**Issue by ajcarrillo** [ecrmnn/collect.js#162]
It could be useful  to search in a `pivot` property when I return a many to many relationship.

**Comment by ecrmnn** [comment]
I’m not following. Are you using collect.js with Adonis or some other Node.js framework?

If you want to extend collect.js outside the scope of this project I suggest you have a look at the macro() method.

**Comment by ajcarrillo** [comment]
```
const collection = collect([
  {product: 'Desk', price: 200, foo:{ bar: 1}},
  {product: 'Chair', price: 100, foo:{ bar: 2}},
  {product: 'Bookcase', price: 150, foo:{ bar: 2}},
  {product: 'Door', price: 100, foo:{ bar: 1}},
]);
```
I'm trying something like this and not working.

`const filtered = collection.where('foo.bar', 1);`

I'm sorry for my bad english

**Comment by ecrmnn** [comment]
Hi, @ajcarrillo 

I like this functionality, but its not supported in Laravel Collections and therefore it's not been added in Collect.js either.

```php
$collection = collect(['product'=>'Desk', 'foo' => ['bar' => 1]]);
//=> Illuminate\Support\Collection {#761
//=>  all: [
//=>    "product" => "Desk",
//=>    "foo" => [
//=>      "bar" => 1,
//=>    ],
//=>  ],
//=> }

$collection->where('foo.bar', 1);
//=> Illuminate\Support\Collection {#753
//=>  all: [],
//=> }
```

You may add it to your project by using the ``macro()`` method.

**Comment by ecrmnn** [comment]
I was a little quick to respond. I see that this is possible in Laravel Collection. I'll have a look at it.

**Comment by ajcarrillo** [comment]
Thank you so much!!!
