### ISSUE TITLE
Pluck return null if value = 0

### ISSUE THREAD

**Issue by khiconit** [ecrmnn/collect.js#173]
I have an array like that : 
`var object = [ { name: 'January', count: 0 },
  { name: 'February', count: 0 },
  { name: 'March', count: 1 },
  { name: 'April', count: 0 },
  { name: 'May', count: 2 },
  { name: 'June', count: 0 },
  { name: 'July', count: 0 },
  { name: 'August', count: 0 },
  { name: 'September', count: 0 },
  { name: 'October', count: 0 },
  { name: 'November', count: 0 },
  { name: 'December', count: 0 } ];`

` var cl= collect(object ).pluck('count');`

it return an array: `[ null, 1, null, 2, null, null, null, null, null, null, null, null ]`

I think that it have some small issue with this pluck function

**Comment by ecrmnn** [comment]
Hi @khiconit.

Thanks for reporting this. This is a bug and should not happen.
I've fixed this and pushed a new version to npm 👍
