### ISSUE TITLE
contains() not identical to Laravel

### ISSUE THREAD

**Issue by cringer** [ecrmnn/collect.js#176]
Not sure if this is by design or not but the contains method is not the same as Laravel.  In Laravel a result will return true if the key OR value contains the item.  The following returns true in Laravel (straight from the Laravel documentation) but false in Javascript:

Laravel 
```php
$collection = collect(['name' => 'Desk', 'price' => 100]);

$collection->contains('Desk');

// true
```

Javascript (I'm using Adonis.js if that matters)
```javascript
const collection = collect({name: 'Desk', price: 100})

collection.contains('Desk')

// false
```

**Comment by ecrmnn** [comment]
Hey, @cringer!

Thank you for discovering this bug.
This is not intentional and should work as in Laravel.

I've pushed a hotfix `4.0.19` that will solve this issue.
