### ISSUE TITLE
Issue in typescript

### ISSUE THREAD

**Issue by ankit20893** [ecrmnn/collect.js#184]
Collect.js is having various warning errors in typescript.

**Comment by ecrmnn** [comment]
Merged a PR that updated the Typescript definitions just a few hours ago. Could you try version 4.0.22 and see if you get the same errors? If not; I’ll change the definitions back.

**Comment by mario-jerkovic** [comment]
> Merged a PR that updated the Typescript definitions just a few hours ago. Could you try version 4.0.22 and see if you get the same errors? If not; I’ll change the definitions back.

There is also an error in TS (version 3.1.6) with `collect([1, 2, 3, 4]).except([2, 12]).all();` as `except` returns `Object`.
