### ISSUE TITLE
import { collect } from 'collect.js' is undefined in typescript

### ISSUE THREAD

**Issue by rohitkhatri** [ecrmnn/collect.js#187]
Importing in `typescript` is not working.

```
import { collect } from 'collect.js';

console.log(collect); // undefined
```

How can I use it in typescript?

**Comment by ecrmnn** [comment]
Hi @rohitkhatri 

This shouldn't be an issue. 🤔

Have you tried without destructuring? 
It's probably not the issue, but worth trying.

**Comment by rohitkhatri** [comment]
I tried using this with this syntex

```
import collect from 'collect.js';
```

And It worked.
