### ISSUE TITLE
Fix typescript typing for the `first` method by adding the default value parameter

### ISSUE THREAD

**Issue by JCWolf** [ecrmnn/collect.js#188]
The `first` method has incomplete definition inside `index.d.ts`. This is the [current implementation](https://github.com/ecrmnn/collect.js/blob/master/index.d.ts#L111). 

It needs the default value parameter:

```typescript
    /**
     * The first method returns the first element in the collection that passes a given truth test.
     */
    first(fn?: (item: Item) => boolean, defaultValue?: any): Item;
```

Also, wouldn't it be better if this library switches to full typescript? Nowadays applications written in JavaScript are very very big and need to be written in typescript in order to avoid errors. JavaScript needs typescript more than ever and big apps need this library more than ever 😄 .
This way we don't have to update the `index.d.ts` manually.

People that use pure JavaScript can still use the built version of the library from the `/dist` folder and typescript people can transpile themselves the library.

**Comment by ecrmnn** [comment]
You're welcome to submit a PR for the TypeScript definition.

Are you seriously suggesting that I rewrite my library to fit *your* needs?
If you don't appreciate this library you can make your own implementation.
Please respect the time and effort that I and other open source maintainers spend on doing this.

**Comment by JCWolf** [comment]
@ecrmnn . I'm sorry. I didn't say I don't appreciate the library, I really appreciate it. It was just a suggestion. Also, moving to Typescript means zero rewriting(only file renaming). I suggested this just to make the library safer.
I will submit a PR soon that will fix this issue.
