### ISSUE TITLE
How about adding ESLint rules?

### ISSUE THREAD

**Issue by g-plane** [ecrmnn/collect.js#19]
Personally, I think ESLint rules is necessary and good for other's contribution.

**Comment by ecrmnn** [comment]
Working on it 👍

**Comment by hiendv** [comment]
I would vote for eslint-config-standard

**Comment by g-plane** [comment]
@hiendv Sounds good! But @ecrmnn uses semi.

**Comment by hiendv** [comment]
Airbnb is my second favorite config then :laughing:

**Comment by BrainMaestro** [comment]
While we're adding eslint configs, could we add prettier too?

**Comment by g-plane** [comment]
@BrainMaestro I think ESLint is enough.

**Comment by BrainMaestro** [comment]
Well, let's see what @ecrmnn thinks. Formatting is much easier with prettier and it can be integrated easily with eslint.

**Comment by g-plane** [comment]
@BrainMaestro You are right.

**Comment by ecrmnn** [comment]
Working on adding eslint for now, but I'll have a look at prettier too.
