### ISSUE TITLE
Problem assigning value with concat()

### ISSUE THREAD

**Issue by gokigoks** [ecrmnn/collect.js#204]
arr1 = collect([1,2,3]);
    arr2 = arr1.isEmpty() ? [] : arr1.concat([4,5]); 

now my intention was to assign a concatenated value to arr2, but arr1 also becomes [1,2,3,4,5]
Is this the intended behavior? how do I assign a concatenated value to another variable without altering the used collection?

version used is 4.3.0

**Comment by ecrmnn** [comment]
Thanks for reporting this. 🙌
This was a bug, and I've pushed a new release (4.4.0). 

Concat should return a new collection but was modifying the existing one.
This should be fixed now.
