### ISSUE TITLE
search fails

### ISSUE THREAD

**Issue by sorenbronsted** [ecrmnn/collect.js#206]
```
const collect = require('collect.js');
const collection = collect([2, 4, 6, 8]);
console.log(collection.search(item => item === 5));

```
return correctly false, but:

`console.log(collection.search((item, key) => item === 5));`

fails with: TypeError: Cannot read property 'toString' of undefined

**Comment by ecrmnn** [comment]
Thanks for reporting.

Fixed in 9af320d41b75c836e9c9d23cc8850e41b19c85d0
