### ISSUE TITLE
Documentation mistake for the keys() function

### ISSUE THREAD

**Issue by janbodnar** [ecrmnn/collect.js#208]
There is a small mistake in the documentation of the `keys()` function.

```
const collection = collect([{
  name: 'Steven Gerrard',
  number: 8,
}, {
  club: 'Liverpool',
  nickname: 'The Reds',
}]);

keys = collection.keys();

//=> ['name', 'number', 'club', 'nickname']
```
The output is: `[ 0, 1 ]`.

**Comment by ecrmnn** [comment]
Hi @janbodnar 

Thanks for reporting. 
This example should use an object instead of an array of objects. That would explain the method better. I'll update it when I got the time.
Feel free to submit a PR.
