### ISSUE TITLE
How to combine two collections of same named objects into a new object?

### ISSUE THREAD

**Issue by jdarling** [ecrmnn/collect.js#212]
This probably won't make sense, but I have a collection of objects similar to:

```
Collection {
  items:
   [ { firstname: 'First',
       lastname: 'Last',
       email: 'Address',
       link: 'Facebook'
       } ] }
```

To get things like Unique Clicks by email I do:

```
const unique = d.groupBy('link').map(l => l.unique('email').count());
Collection {
 items:
  { Facebook: 2,
    Twitter: 2 } }
```

Total link clicks:

```
const total = d.countBy('link');
Collection {
 items:
  { Facebook: 2,
    Twitter: 4 } }
```

But how would I get back a collection that had the total links and the unique clicks?

```
Collection {
 items:
  { Facebook: {
      total: 2,
      unique: 2
    },
    Twitter: {
      total: 4,
      unique: 2
    } } }
```

Also, and this is probably a feature request, let me know and I'll file it as such, is there a way to group with sub grouping in a single command?  Something like `d.groupBy('link', 'email')`

**Comment by ecrmnn** [comment]
Both `groupBy()` and `countBy()` returns a new collection.
You could `merge()` them like this perhaps `unique.merge(total)`

**Comment by jdarling** [comment]
Guess I should have mentioned I tried that, actually got a very unexpected result:

```
Collection {
  items:
   { Facebook: 2,
     Twitter: 2,
     items:
      { Facebook: 2,
        Twitter: 4 } } }
```

**Comment by ecrmnn** [comment]
Try this

```js
collection
  .groupBy('link')
  .map(link => (
    { total:link.count(), unique: link.unique('email').count() }
  ));
```

**Comment by jdarling** [comment]
That works, I was blinded by the obvious route and totally didn't pay attention to alternative approaches.  Thanks.
