### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jdarling** [ecrmnn/collect.js#213]
I believe I've found a typo in the docs that probably no one but me will have noticed.

```
mapSpread()
The mapSpread method iterates over the collection's items, passing each nested item value into the given callback. The callback is free to modify the item and return it, thus forming a new collection of modified items:

const collection = collect([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
 
const chunks = collection.chunk(2);
 
const sequence = chunks.mapSpread((odd, even) => {
    return odd + even;
});
 
sequence.all();
 
//=> [1, 5, 9, 13, 17]
```

The typo is `const sequence = chunks.mapSpread((odd, even) => {` should be `const sequence = chunks.mapSpread((even, odd) => {`  See the first iteration 0 is passed as the first argument (although mathematically zero is neither odd nor even) and 1 is passed as the second argument.  Every iteration after that is the same with the even number being passed first and the odd second.  The other way to "fix" this would be to remove 0 from the collection.

**Comment by ecrmnn** [comment]
I've got the parameter names mixed up in the example.
It should have been `.mapSpread((even, odd)) =>`
[Laravel Docs](https://laravel.com/docs/master/collections#method-mapspread)

```js
> const collection = collect([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
undefined

> const chunks = collection.chunk(2);
undefined

> const sequence = chunks.mapSpread((odd, even) => {
...     console.log('odd', odd);
...     console.log('even', even);
...     return odd + even;
... });
odd 0
even 1
odd 2
even 3
odd 4
even 5
odd 6
even 7
odd 8
even 9
>
```
