### ISSUE TITLE
TypeError: values.map is not a function

### ISSUE THREAD

**Issue by rafaelgfirmino** [ecrmnn/collect.js#216]
When I try to run the flatmap example I have an error occurring.
```
TypeError: values.map is not a function
```
Initially this problem occurred in typescript, so I tried to simulate in vue without the typescript, but I have the same problem.

```
<template></template>

<script>
import collect from 'collect.js'
export default {
  name: "App",
  created(){
     const collection = collect([
          { name: 'Robbie Fowler' },
          { nickname: 'The God' },
          { position: 'Striker' },
      ]);

      const flatMapped = collection.flatMap(values => values.map(value => value.toUpperCase()));
    
      console.log(flatMapped.all());
  }
};
</script>
```
https://codesandbox.io/s/vue-template-njvme?fontsize=14

**Comment by ecrmnn** [comment]
Hi @rafaelgfirmino 

I've tested this.
Theres is an error in the documentation, so the example isn't working.
However, the `flatMap` method is working correctly

**Comment by rafaelgfirmino** [comment]
Thanks for the answer.
