### ISSUE TITLE
Can't create a collection in Angular 8

### ISSUE THREAD

**Issue by s-patompong** [ecrmnn/collect.js#227]
Hi,

I've been trying to use collect.js in Angular but I keep getting an error says 'collect_js_1.collect is not a function' when I try to create a collection using `collect()` method.

I pulled down collect.js version 4.16.6. I also created an example code on stackblitz showing an error on the console when the code tries to create a new collection in ngOnInit() method.

Here is the link to stackblitz: https://stackblitz.com/edit/collectjs-initiate-problem

Any suggestion?

**Comment by ecrmnn** [comment]
Try this
```ts
import collect from 'collect.js';
```

**Comment by s-patompong** [comment]
Thank you for fast response, tried it and can confirm that it works!

Just want to point this out for other Angular fellows. If you want to import both `collect` and `Collection`, you need to do it like this to make it work:

```javascript
import collect, { Collection } from 'collect.js';
```

I'll close the issue now.

**Comment by ecrmnn** [comment]
Great! Personally I don't use TS a lot, but I enjoyed the syntax more in the non-working example. If you want to submit a PR to add exporting `collect`, I'm open to it. If you do please add tests that proves they're all the same instance of `Collection`

**Comment by s-patompong** [comment]
That sounds good, I'll try to work on it :)

**Comment by s-patompong** [comment]
@ecrmnn I've looked into it. The only way to make TS import it as a non-working example I've shown you before is to wrap the collect inside a bracket like so
```javascript
// src/index.js:131
module.exports = { collect };
```
Doing this will make it possible for TS file to import the collect in like `import { collect } from 'collect.js'`. However, it breaks the collect import in JS file, it will only work if API consumer import it like so
```javascript
// test/tests.js:8
const { collect } = require('../dist');
```

I don't think it's worth the change. Also, I learned that TS user can do it another way around like this if they want the `collect` to be inside the '{}'
```javascript
import { default as collect, Collection } from 'collect.js';
```

**Comment by ecrmnn** [comment]
I see. I'm currently on vacation so I try it out, but I thought adding a new export would solve it. 
```js
const collect = collection => new Collection(collection);

module.exports = collect;
module.exports.collect = collect;
module.exports.default = collect;
```

**Comment by s-patompong** [comment]
Have fun on your vacation! don't worry I'll try it out for you.
