### ISSUE TITLE
Question about groupBy

### ISSUE THREAD

**Issue by iiDestiny** [ecrmnn/collect.js#233]
Why does the result returned by `groupBy` have a items child element?

![image](https://user-images.githubusercontent.com/17637481/67453198-82970100-f658-11e9-87f9-ae55de5a1429.png)
![image](https://user-images.githubusercontent.com/17637481/67453212-917db380-f658-11e9-969f-54fb07e663cc.png)

**Comment by ecrmnn** [comment]
`groupBy()`groups items into an array of objects.
Have a look at the differences between `groupBy()` and `keyBy()`

https://collect.js.org/api/groupby.html
https://collect.js.org/api/keyby.html

**Comment by ecrmnn** [comment]
Hmm. 
Can you provide the data you're working with?
It's original state, and what you would like to transform it too?

**Comment by iiDestiny** [comment]
For example, I used to get data like this.

```
area_services[1][0].id
```

After collect.js conversion

```
area_services[1].items[0].id
```

Maybe I didn't understand the design idea, but I feel that "items" is not very convenient when I use it.
Sorry to bother you.

**Comment by ecrmnn** [comment]
No worries at all.
A `Collection` always have `items`, thats how everything is implemented.
When calling `all()` you should get a plain `array` or `object` back.

```js
collect([1, 2, 3])
// Collection { items: [ 1, 2, 3 ] }
// Returns an instance of Collection with items

collect([1, 2, 3]).all()
// [ 1, 2, 3 ]
// Returns a plain array
```

If you provide the actual data you're working with I can try to help you.

**Comment by iiDestiny** [comment]
raw data

```
{
    "area_services": [
        {
            "id": 1,
            "client_game_id": 1,
            "title": "一区",
            "sort": 1,
            "created_at": null,
            "updated_at": null,
            "laravel_through_key": 1
        }
    ]
}
```
Then I want to group by id

```
const data = collect(area_services).groupBy('id').all()
```

Then I get

![image](https://user-images.githubusercontent.com/17637481/67467379-38734700-f67b-11e9-8e31-20dd129b7293.png)

I don't want to get `items` but I have executed the `all()` method

**Comment by iiDestiny** [comment]
raw data

```
{
    "area_services": [
        {
            "id": 1,
            "client_game_id": 1,
            "title": "一区",
            "sort": 1,
            "created_at": null,
            "updated_at": null,
            "laravel_through_key": 1
        }
    ]
}
```
Then I want to group by id

```
const data = collect(area_services).groupBy('id').all()
```

Then I get

![image](https://user-images.githubusercontent.com/17637481/67467379-38734700-f67b-11e9-8e31-20dd129b7293.png)

I don't want to get `items` but I have executed the `all()` method

**Comment by ecrmnn** [comment]
Could you please provide raw data, not images before and after `_.groupBy(area_services, 'id')` ?

**Comment by iiDestiny** [comment]
I looked at the source code and found that the child elements grouped by `groupBy` are also Collection objects.

```
const data = [
        {
            "id": 1,
            "client_game_id": 1,
            "title": "一区",
            "sort": 1,
            "created_at": null,
            "updated_at": null,
            "laravel_through_key": 1
        }
    ]

collect(data).groupBy('id').all()
```
result

```
{
    1: Collection
        items: Array(1)
            0:
            client_game_id: (...)
            created_at: (...)
            id: (...)
            laravel_through_key: (...)
            sort: (...)
            title: (...)
           updated_at: (...)
}
```

**Comment by iiDestiny** [comment]
I need this to achieve the desired result.

```
collect(data).groupBy('id').map(items => items.all()).all()
```

![image](https://user-images.githubusercontent.com/17637481/67472872-57c2a200-f684-11e9-9e08-0588ceef65ba.png)

**Comment by iiDestiny** [comment]
thank you very much！
