### ISSUE TITLE
Missing functionality: toObject

### ISSUE THREAD

**Issue by Yahav** [ecrmnn/collect.js#236]
Javascript arrays can't contain custom keys, for that we have objects.
Now imagine you have a collection of an object with string keys and object values. 
If you'll use toArray the string keys will be lost.
Am i missing something or there isn't method to get an actual object of the collection?
(i understand that this is a js port of laravel collection, but laravel collection doesn't require this functionality of course since php arrays can have custom keys)

**Comment by ecrmnn** [comment]
Have to had a look at the [`all()`](https://collect.js.org/api/all.html) method?

**Comment by Yahav** [comment]
That worked
