### ISSUE TITLE
Dot Notation for `put()`, `has()`, `get()` possible?

### ISSUE THREAD

**Issue by marcus-at-localhost** [ecrmnn/collect.js#239]
I kind of missing the overall use of dot notation in some key methods. It's quite awkward to do `collect({}).put('foo', { bar: { a: true }});` instead of just `collect({}).put('foo.bar.a', true);` or `collect({foo: { bar: { a: true }}}).get('foo.bar.a')`. Or do I miss something?

**Comment by ecrmnn** [comment]
Collect.js offers an identical api to Laravel collections. Laravel does not offer dot notation in these methods.

If you would like to add this functionality you can do so for your own projects using the [`macro`](https://collect.js.org/api/macro.html) method

### Laravel collection
```php
collect([])->put('foo.bar.a', true)->all();

// [
//     "foo.bar.a" => true,
// ]
```

I've even submitted a [PR](https://github.com/laravel/framework/pull/29458) for this.
```php
collect(['foo' => ['bar' => 'baz']])->get('foo.bar');

// null
```

```php
collect(['foo' => ['bar' => 'baz']])->has('foo.bar');

// false
```

**Comment by marcus-at-localhost** [comment]
@ecrmnn my apologies. I was sure dot notation was possible, but I guess I was just getting around that, using laravel array helpers. Thanks for pointing out, using macros!
