### ISSUE TITLE
Difference between Firefox and Chrome, when trying to .sortBy('nonExistingKey')

### ISSUE THREAD

**Issue by marcus-at-localhost** [ecrmnn/collect.js#243]
I'm not sure what the correct fallback is, but if I try to sort an array of objects by an undefined key, this happens:

```js
{
  var x = collect([
    {label: "1"},
    {label: "11"},
    {label: "12"},
  ]).sortBy('label2').values();

  console.log(x);
}
```
Using `"collect.js": "^4.20.2",`

Firefox Developer Ed. 73

![image](https://user-images.githubusercontent.com/1337223/73590330-89e46b00-44e1-11ea-888d-296ee22af9a4.png)

Chrome 79

![image](https://user-images.githubusercontent.com/1337223/73590358-d6c84180-44e1-11ea-98ca-f53acac4b664.png)

Latest Edge (EdgeHTML rendering engine)

![image](https://user-images.githubusercontent.com/1337223/73590474-00ce3380-44e3-11ea-8930-06851ec50282.png)

I caught it, because we dropped a 'sortKey' key from an array of objects and while I didn't noticed anything, using Chrome for most of the time, by using Firefox more, I noticed this weird behavior.

I guess fallback order should be the array index, but why is Firefox reversing it?

**Comment by ecrmnn** [comment]
I think this has something to do with how browsers implements `sort`

Could you try the same with the build from this feature branch?
https://github.com/ecrmnn/collect.js/commit/d34f93a3433d6b6fa0df6a7b58ebf30a0c06d760

**Comment by marcus-at-localhost** [comment]
Unfortunately this had no effect (if I did everything right) https://jsfiddle.net/op8xr4hg/

**Comment by marcus-at-localhost** [comment]
Ok, I tried to debug this like a caveman (without building it myself) and here is what I came up with:
`a` and `b` in `collection.sort(function (a, b) {...}` is flipped in Firefox.

Chrome: 

![image](https://user-images.githubusercontent.com/1337223/74443024-c9f90580-4e72-11ea-8c79-4a097411bd33.png)


Firefox

![image](https://user-images.githubusercontent.com/1337223/74443131-fa40a400-4e72-11ea-917b-6b5aaa2624f8.png)

here is another case, that illustrates it a bit better

```js
{
  let x = [12,111,2,3,1,13].sort((a,b) => {
  console.log(a,b);
  return 0;       
  })

  console.log(x)
}
```

Chrome

![image](https://user-images.githubusercontent.com/1337223/74444574-5e646780-4e75-11ea-8c85-6f7d45ddce22.png)



Firefox

![image](https://user-images.githubusercontent.com/1337223/74444529-4c82c480-4e75-11ea-940f-3c582ce3dd92.png)

`[].sort((a,b)` a,b params are flipped and since collect.js checks first for valueA

```js
    if (valueA === null || valueA === undefined) {
      return 1;
    }
```

the order is determined by that value.

So I guess the question is - what should happen if the `key` to `.sortBy()` is `undefined`? Probably not change the order at all and therefore `return 0;`?

At this point, I have no idea what other cases the first two if statements are dealing with.

I hope that helped a bit

**Comment by ecrmnn** [comment]
How can we write a test to prove this? 🤔

**Comment by marcus-at-localhost** [comment]
I'm out of ideas regarding writing tests. All articles I found[1] are talking about "Browsers different sorting algorithms", but I'm not that deep into JS to draw any conclusions from this, I'm sorry. :) - I hope someone with more insight will find this.
[1] https://alistapart.com/article/what-i-talk-about-when-i-talk-about-sorting/

**Comment by ecrmnn** [comment]
@marcus-at-localhost  I'm going to investigate further on this in the future, but I'm closing this for now. It bugs me to have this issue open :)
