### ISSUE TITLE
Impossible to extend

### ISSUE THREAD

**Issue by Garanaw** [ecrmnn/collect.js#244]
I personally am a fan of newing objects myself rather than using helpers "de facto", because it allows some flexibility, like for example extending the classes (the Collection in this casae).

However, currently it is not possible as the only exported function is the helper.

Would it be possible to add the Collection class to the exported list? Something like

```
module.exports = collect;
module.exports.collect = collect;
module.exports.default = collect;
module.exports.Collection = Collection;
```

This way, it would allow users to extend the Collection with custom methods:

```
import Collection from 'collect.js';

Collection.prototype.whateverMethod = require('./myCustomMethod');

let customCollection = new Collection(myArray);
let whateverResult = customCollection.whateverMethod(item => doSomething(item));
```

**Comment by ecrmnn** [comment]
Hi, @Garanaw 

Have you tried extending with the [`macro()`](https://collect.js.org/api/macro.html) method?

**Comment by Garanaw** [comment]
Hi @ecrmnn 

Thanks for the suggestion, it's definitely something I didn't think about, and that might solve the part of extending the collections.

However, that approach would still leave a couple of holes:

- Validation: we're not able to do `something instanceof Collection`.
- Extension: When using in combination with [this package](https://github.com/milroyfraser/sarala) you cannot override the `newCollection` method in your models to wrap each type in custom collections, which is the Laravel-ish way.

Still, I think that'd be possible by using classes, not sure if the package can be extended when using functions

**Comment by boris-glumpler** [comment]
I'd also like for `Collection` to be exported. I'm currently working on a project that uses collect.js and would like to check in my tests that some properties are indeed an instance of `Collection`. My tests obviously won't fail without these checks, but that little OCD voice in my head is certainly complaining ;)

**Comment by ecrmnn** [comment]
I'm open to merging a PR with this. Make sure to include tests and documentation 👍
