### ISSUE TITLE
The sum method encountered problems when calculating floating point numbers

### ISSUE THREAD

**Issue by LiXunGuan** [ecrmnn/collect.js#245]
```javascript
const collection = collect([
  { name: 'My story', pages: 0.1},
  { name: 'Fantastic Beasts and Where to Find Them', pages: 0.2},
]);

collection.sum('pages'); // 0.30000000000000004
```
Suggestion reference https://github.com/nefe/number-precision

**Comment by ecrmnn** [comment]
Thanks for reporting 🙌

I believe this is an issue with JavaScript itself and not Collect.js.
I have to think about what I want to do about his.

**Comment by ecrmnn** [comment]
Fixed in `4.23.0`

**Comment by patrickomeara** [comment]
This fix is throwing errors for decimals in strings.

```ts
const collection = collect([
  { name: 'My story', pages: '0.1'},
  { name: 'Fantastic Beasts and Where to Find Them', pages: '0.2'},
]);

collection.sum('pages'); 
```

This previously worked.

**Comment by ecrmnn** [comment]
Thanks for reporting! Fixed in https://github.com/ecrmnn/collect.js/commit/b54f4b66afd3762cdcf0dbb1fc673dfe8359f556 and added [test](https://github.com/ecrmnn/collect.js/blob/master/test/methods/sum_test.js#L63)
