### ISSUE TITLE
.every is not consistent with Array.every

### ISSUE THREAD

**Issue by matrunchyk** [ecrmnn/collect.js#246]
Hello! Thank you for your amazing work you do here!!!

Not sure if it's a feature or bug, but I noticed that `collect().every` and `Array.every` have different behavior. 

The thing is that `Array.every` stops checking once the callback's value is false, when `collect().every` continues checking all the elements. What is the idea behind checking the rest of elements since it knows that the result is `false`?

**Comment by ecrmnn** [comment]
Hi, @matrunchyk 
Thanks for your kind words.

This is probably a bug and `every()` should be refactored to use early return if the tests would pass.
I don't have the time to fix this right now but PRs welcome 👍

**Comment by ecrmnn** [comment]
https://github.com/ecrmnn/collect.js/commit/c25bd819f69fe576d6e7af94449c4e274d7d821d

**Comment by matrunchyk** [comment]
Wow it was faster that I have even started creating the PR! Thanks!!!
