### ISSUE TITLE
Reduce *.min.js size?

### ISSUE THREAD

**Issue by marcus-at-localhost** [ecrmnn/collect.js#248]
Hi, I wonder if it's possible to reduce the size of the minified version.
As far as I understand (or what I read, I've never used webpack) those eval statements are in there to reduce build time and bundling source maps or something, but is this necessary for the final build? Am I doing it wrong? (most of the time I'm pulling collect.js in from jsdelivr....) Or does it not matter? Thanks!

**Comment by ecrmnn** [comment]
Tbh I'm not sure. I'm not a webpack wizard I just wanted to offer a minified version. But I'm definitely open to reducing the minified version. A PR is very welcomed if you find a way to reduce the bundle size

**Comment by marcus-at-localhost** [comment]
I just parroted what I found on SO https://stackoverflow.com/a/39164038/814031 :)
I've never used Webpack, but I've seen those eval() statements a few times in other libraries and was wondering if that is really necessary for production code.
Maybe this helps: https://webpack.js.org/configuration/devtool/

**Comment by marcus-at-localhost** [comment]
Got collect.min.js down from 99kb to 38kb :)
I guess it's ok to leave collect.js in development mode incl. all the source maps etc?!

**Comment by ecrmnn** [comment]
Nice! Yeah I think its OK to leave collect.js i dev mode. I'll have a look at it :)
