### ISSUE TITLE
How can i set the return of a collect to a typescript interface?

### ISSUE THREAD

**Issue by tugzera** [ecrmnn/collect.js#250]
[SOLVED]

I have this interface:

interface UF {
  id: number;
  initials: string;
  name: string;
}

This state:
const [uf, setUf] = useState<UF[]>([]);

I want to sort my array of UF's by name using collect and set the value to my State: 

// const sorted = collect<UF[]>(arrayUf).sortBy('name); WRONG

sorted = collect(arrayUf).sortBy('name').toArray() as UF[];
setUf(sorted);

But i'm getting unknow type error... someone could help me?

**Comment by ecrmnn** [comment]
Don't do TS personally. Adding [help wanted]
