### ISSUE TITLE
The sum method issues

### ISSUE THREAD

**Issue by LiXunGuan** [ecrmnn/collect.js#251]
```javascript
        const collection1 = collect([
            {
                amount: -6.18,
                name: 'zhangsan',
            },
            {
                amount: -9888,
                name: 'lisi',
            },
            {
                amount: 9888,
                name: 'wangwu',
            },
            {
                amount: 6.18,
                name: 'zhaoliu',
            }
        ]);


        const collection2 = collect([
            {
                amount: -6.18,
                name: 'zhangsan',
            },
            {
                amount: 6.18,
                name: 'zhaoliu',
            },
            {
                amount: -9888,
                name: 'lisi',
            },
            {
                amount: 9888,
                name: 'wangwu',
            },
        ]);

        console.log(collection1.sum('amount'));  // -2.91322521662e-13
        console.log(collection2.sum('amount'));  // 0
```

**Comment by ecrmnn** [comment]
This seems to be a fundamental flaw in JS. 
Would be happy to consider a solution.
PRs welcome. 

```js
[-6.18,-9888,9888,6.18].reduce((acc, num) => acc += num)
// -2.913225216616411e-13

[-6.18, 6.18, -9888, 9888].reduce((acc, num) => acc += num)
// 0
```

**Comment by kgryte** [comment]
This is **not** a fundamental flaw in JS. It is well known that, in general, when performing arithmetic operations in floating-point arithmetic, operations are not associative. There is no bug to fix here; this behavior should be expected.

If your operands are in random order and are of varying magnitude, use [compensated summation](https://github.com/stdlib-js/stdlib/blob/f4f160affa9237acd0ac84239af8af02cb7f5f80/lib/node_modules/%40stdlib/blas/ext/base/dsumkbn/test/test.dsumkbn.js#L63). Note, however, that no particular summation technique is a silver bullet. The optimal summation algorithm depends on the nature and order of the data being operated on.

The recommendation of using `decimal.js` is not advised as equivalent results can be achieved using floating-point arithmetic with far better performance.

**Comment by kgryte** [comment]
As an addendum, I would advise against making [compensated summation](https://github.com/stdlib-js/stdlib/blob/f4f160affa9237acd0ac84239af8af02cb7f5f80/lib/node_modules/%40stdlib/blas/ext/base/dsumkbn) the default summation technique, because, to reiterate, no summation algorithm is universally optimal. For example, compensated summation algorithm can have worse accuracy on sorted datasets.

**Comment by ecrmnn** [comment]
Thanks for clearing that up @kgryte 
I phrased myself poorly but tried to say that this probably a language thing/intended and should be solved outside of this library. I don't have that much experience working with arithmetic so thanks again for your explanation 👍
