### ISSUE TITLE
Support for `skipUntil` and `skipWhile`

### ISSUE THREAD

**Issue by sohaibalam67** [ecrmnn/collect.js#255]
#### skipUntil
The skipUntil method skips items until the given value is found and then returns the remaining items in the collection:
```
collect([1, 1, 2, 2, 3, 3, 4, 4]).skipUntil(2);
// [2, 2, 3, 3, 4, 4]
```
Also, skipUntil method skips items until the given callback returns `true` and then returns the remaining items in the collection:

```
collect([1, 1, 2, 2, 3, 3, 4, 4]).skipUntil(item => item >= 2);
// [2, 2, 3, 3, 4, 4]
```
Laravel equivalent: https://laravel.com/docs/7.x/collections#method-skipuntil

#### skipWhile
The skipWhile method skips items while the given value is found and then returns the remaining items in the collection:
```
collect([1, 1, 2, 2, 3, 3, 4, 4]).skipWhile(1);
// [2, 2, 3, 3, 4, 4]
```
Also, skipWhile method skips items while the given callback returns `true` and then returns the remaining items in the collection:

```
collect([1, 1, 2, 2, 3, 3, 4, 4]).skipWhile(item => item < 2);
// [2, 2, 3, 3, 4, 4]
```
Laravel equivalent: https://laravel.com/docs/7.x/collections#method-skipwhile

---
These methods were added in Laravel 7.x

NOTE: If it is approved, I can open a PR.

**Comment by ecrmnn** [comment]
Thanks for the heads up. 
Merged https://github.com/ecrmnn/collect.js/commit/f0fdde1a90f7ffcfc9a2935116e50e361c81d65b

**Comment by sohaibalam67** [comment]
> Thanks for the heads up.
> Merged [f0fdde1](https://github.com/ecrmnn/collect.js/commit/f0fdde1a90f7ffcfc9a2935116e50e361c81d65b)

Oh! you already did it!
I thought I could take this up, had already finished it, but didn't open the PR, waited for your approval!
I'm just beginning to contribute to the open-source projects I use and find really useful.
Nevermind! Maybe next time!
And yeah, the source is really really good! simple and clean.

**Comment by ecrmnn** [comment]
Hehe, yeah I had it sitting in a branch but hadn't finished it yet.
Feel free to contribute next time :)

**Comment by sohaibalam67** [comment]
Thought so!
Sure 😄
