### ISSUE TITLE
Push & pull modify the original array/object

### ISSUE THREAD

**Issue by brentkelly** [ecrmnn/collect.js#259]
Firstly - great project btw. Laravel collections are awesome & I was very happy when I came across it.

One issue I've noticed is that when you `push` to a collection it modifies the original source array. This seems like very unexpected behavior. It certainly doesn't line up with `Illuminate\Collection`.

```javascript
const foo = [1, 2, 3];
const bar = collect(foo).push(4);
console.log(foo); // [1, 2, 3, 4] <--- woah ... didn't expect that!
```

Surely `foo` should be unchanged on `[1, 2, 3]` while the underlying array in the collection `bar` should contain `[1, 2, 3, 4]`. I would expect the original input passed to the constructor to be cloned so it doesn't get modified by the operations of the collection pipeline?

Take this basic use case for a collection pipeline: say you have an array along with a couple of other numeric variables. You want to retrieve from it all a single array of all truthy values without modifying the original variables. I would usually expect to do this:

```javascript
const foo = [1, 2, 3, null];
const bar = 0;
const baz = 4;

// grab an array of all non-false values
const result = collect(foo)
    .push(bar)
    .push(baz)
    .filter();

console.log('Result is:', result.all(), 'and foo is:', foo);
// Result is: [1, 2, 3, 4] and foo is: [1, 2, 3, null, 0, 4]
```

To further complicate the situation `merge` works differently - how you would expect it to - by not modifying the source variables. And for icing on the cake - if you `push` *after* merging, it now no longer modifies the original array.

```javascript
const foo = [1, 2, 3, null];
const bar = [4, 5, 6, ''];
const baz = 7;

// grab an array of all non-false values
const result = collect(foo)
    .merge(bar)
    .push(baz)
    .filter();

console.log('Result is:', result.all(), 'and foo is:', foo); 
// Result is: [1, 2, 3, 4, 5, 6, 7] and foo is: [1, 2, 3, null]
```

Of the methods I've tested I've noticed the issue also exists with `shift`, and on objects with `put` and `pull`.

This produces some bizzare bugs where you whip out a collection pipeline to process a bunch of data and then start getting unexpected errors where you have accidentally modified all the original variables without realizing.

My suggestion is that either the constructor - or perhaps just affected methods if there's only a few - should shallow clone the array or object to avoid modifying the original source input.

... although I do appreciate that with use of this library being pretty widespread that ship may have sailed if there is too much code that expects this behavior now.

**Comment by ecrmnn** [comment]
Thanks for reporting this.
Since objects/arrays are passed by reference this happens. 

We don't copy the value when calling `collect(variable)`.
Calling `push` would then mutate `variable`.

Fixing this would potentially cause new issues in other projects.
I think this needs to be part of a major release if it's going to be fixed.

I'm going to close this and think about it.
Thanks again for reporting!

**Comment by brentkelly** [comment]
@ecrmnn agree re causing issues in other projects & being part of a major release.

One suggestion I would have is that until then perhaps it is worth noting it in the documentation - as the comparisons to Laravel create the natural expectation it will work the same.

Thanks!
