### ISSUE TITLE
Support async functions

### ISSUE THREAD

**Issue by stasbamiza** [ecrmnn/collect.js#260]
I wonder your lib it's like a Laravel collections ;)

I tested collection with *async* functions, added *await* but it not work.

Do you plan add support for async functions?

**Comment by ecrmnn** [comment]
Why would you use `await`?

**Comment by stasbamiza** [comment]
Now I work *Selenium Webdriver* that have multiple nested consistent `async` collections. For my target important do all operations step by step. Now I created nested loops that do work bu I know that this can be look not so ugly and after several searchements I found * collect.js * that can make code more beauty.

**Comment by ecrmnn** [comment]
Ok, I understand. At the moment I don't plan to support async/await, but PRs are welcome :)
