### ISSUE TITLE
'has' method return wrong result

### ISSUE THREAD

**Issue by ndinhbang** [ecrmnn/collect.js#264]
i have below code: https://runkit.com/ndinhbang/5fab75f6f8205200133e3273

```
const collect = require("collect.js")
let arr = ['aaa'];
let fliped = collect(arr).flip();
let hasItem = fliped.has('aaa');
```

the expected result is `true`, but it actually return `false`

**Comment by Kassaila** [comment]
Hi, @ndinhbang.
This PR #265  will resolve problem with method 'has'.
In your example, if checking property first element in array, after `flip` return the object: `{  'aaa': 0 }`.
After `has`, checking return a value of key. In your case value `0`, thats equates to `false`.
All keys with negative values like: `0`, `null`, `undefined`, `''`, `false` - will return `false`.

I hope that helped.

**Comment by ecrmnn** [comment]
Closed in 9a94695

**Comment by ndinhbang** [comment]
@Kassaila thank you so much! 
I think we can use `Object.prototype.hasOwnProperty.call(_this.items, key)`  instead of  `Object.keys(_this.items).includes(key)`
for better performance, right ?

**Comment by Kassaila** [comment]
@ndinhbang Yes we can. If it gives the best performance, on a lot of operations with the method `has`.

**Comment by ecrmnn** [comment]
✅ `hasOwnProperty` https://github.com/ecrmnn/collect.js/commit/02dff133957eb398f31aca899138a76603316491

**Comment by ndinhbang** [comment]
@ecrmnn @Kassaila thank you
