### ISSUE TITLE
Key not defined when using sum

### ISSUE THREAD

**Issue by Soletiq** [ecrmnn/collect.js#273]
The key is undefined when using `sum`. One would expect that if you could map over the values, you could also get the key.

```
return collect(data)
  .sum((value, key) => {
    // key is undefined here
  });
```

**Comment by ecrmnn** [comment]
Hey @Soletiq 

This is working as intended. 
We follow the convensions in Laravel collections - and it's not possible to get the key when using `sum`.
[See documentation](https://laravel.com/docs/8.x/collections#method-sum)
If you need the key you need to use a different method.
