### ISSUE TITLE
sole() needs implemented

### ISSUE THREAD

**Issue by michaellburchett** [ecrmnn/collect.js#277]
Looking to get involved in some open source projects and wondering if it would be beneficial for me to take a crack at implementing these last few that were not yet implemented from Laravel, starting with containsStrict()?

"The contains method uses "loose" comparisons when checking item values, meaning a string with an integer value will be considered equal to an integer of the same value. Use the containsStrict method to filter using "strict" comparisons."

**Comment by ecrmnn** [comment]
Hi, @michaellburchett 

Great that you want to contribute! In collect.js all methods are strict by default, meaning that `contains()` is already strict and removes the need for `containsStric()`. You can see which methods and why we've chosen this approach here; https://github.com/ecrmnn/collect.js#strictness-and-comparisons

If you want to contribute here are a few methods you could implement
Some methods that are currently missing;
- `sole` https://laravel.com/docs/8.x/collections#method-sole
- `chunckWhile` https://laravel.com/docs/8.x/collections#method-chunkwhile

**Comment by michaelb-kr** [comment]
@ecrmnn  Ok, sounds good. I can close this one and volunteer to take up .sole() then. Thanks!

**Comment by michaellburchett** [comment]
@ecrmnn Ok, sounds good. I can close this one and volunteer to take up .sole() then. Thanks!

**Comment by stevebauman** [comment]
PR has been submitted: https://github.com/ecrmnn/collect.js/pull/280

**Comment by ecrmnn** [comment]
Merged, https://github.com/ecrmnn/collect.js/commit/53483311b63db6dde31cf1d13e9aae612a72c734
