### ISSUE TITLE
Pluck on Nested Arrays Help

### ISSUE THREAD

**Issue by mecjos** [ecrmnn/collect.js#298]
Hi, 

I'm trying to use pluck method on my nested array objects.. My structure is same as in docs but mine gets only first object of child array. my object array structure is as follows 

https://ibb.co/7W7NcRS

And I try to collect sizes with following code;

`const totalSizePartCads = collect(this.parts).pluck('cads.*.size').sum()`

I want to sum sizes in parts object array below.

```
parts = [
    { name: 'part name 1', cads: [ {name: 'name 1', size: 1024} ] },
    { name: 'part name 2', cads: [ {name: 'name 2', size: 1024} ] },
    { name: 'part name 3', cads: [ {name: 'name 3', size: 1024} ] },
    ...
    ...
    ...
]
```

Where is my mistake? Thank you..

**Comment by mecjos** [comment]
Hi @ecrmnn thanks for your reply.. I solved it by adding collaps method as follows:

`const totalSizePartCads = collect(this.parts).pluck('cads').collapse().pluck('size').sum()`

Thank you

**Comment by ecrmnn** [comment]
🙌
