### ISSUE TITLE
how does this differ from lodash?

### ISSUE THREAD

**Issue by afghl** [ecrmnn/collect.js#3]
hi, ercmnn. 

i am just confused, how does this differ from lodash?

**Comment by mikebronner** [comment]
Mostly in the syntax. You can do all this with lodash if you like. Its a convenience for Laravel users, from what I understand. :) I'll let @ecrmnn answer officially, though.

**Comment by ecrmnn** [comment]
Hi, Afghl.

As @mikebronner said it's mostly in the syntax. ``Collect.js`` is a JavaScript port of [Laravel collections](https://laravel.com/docs/5.4/collections). You can use lodash or underscore if you'd like, but if you want a similar way to work with arrays/objects on your backend and frontend this is a nice way to achieve that.
