### ISSUE TITLE
Support esm?

### ISSUE THREAD

**Issue by peterroe** [ecrmnn/collect.js#300]

**Comment by ecrmnn** [comment]
Sure, I'll be more than happy to review a PR. Please feel free to submit one 😄

**Comment by peterroe** [comment]
I'm interested in trying to refactor it, and I'm going to refactor using `vite` and `vitest`, can I do this？

**Comment by ecrmnn** [comment]
Why would you need Vite to support ESM? Is there something I’m missing here?

**Comment by peterroe** [comment]
No, it's purely due to personal habits, but other than that, vite and vitest are faster and have more features, and make the refactored project more "younger"

**Comment by ecrmnn** [comment]
Would appreciate a PR. Please keep it vanilla without any dependencies 😊

**Comment by peterroe** [comment]
OK,  I am also think we shouldn't change to much,maybe I should create a new repo like `collect-es.js`?

**Comment by peterroe** [comment]
I create a new repo to support `esm`😊 : https://github.com/peterroe/collect-es
