### ISSUE TITLE
Method `reduce` with `key/index`

### ISSUE THREAD

**Issue by SDIjeremy** [ecrmnn/collect.js#311]
Currently it is not possible to access the Key/Index of the item while using `reduce()`

```php
$collection->reduce(function ($carry, $value, $key) use ($ratio) {
    return $carry + ($value * $ratio[$key]);
});
```
https://laravel.com/docs/9.x/collections#method-reduce

**Comment by ecrmnn** [comment]
Hi.
Thanks for reporting.
Could you please provide an example on Runkit?

https://npm.runkit.com/collect.js

**Comment by jjjrmy** [comment]
> Hi. Thanks for reporting. Could you please provide an example on Runkit?

https://runkit.com/embed/t67a6zx0ng4g

**Comment by SDIjeremy** [comment]
Can you please check my PR, it says it failed but I can't see the error.
