### ISSUE TITLE
Question: How to return an array of objects with only particular keys?

### ISSUE THREAD

**Issue by Mashiane** [ecrmnn/collect.js#324]
Hi

Lets just say you have an array of objects.

var movies = [
  {
    "name": "The Shawshank Redemption",
    "outline": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "rating": 9.3,
    "director": "Frank Darabont",
    "year": 1994,
    "stars": [
      "Tim Robbins",
      "Morgan Freeman",
      "Bob Gunton"
    ],
    "runtime": 142,
    "genre": [
      "Crime",
      "Drama"
    ],
    "certificate": "R",
    "date": "1974-04-30T10:29:29+05:30",
    "actor": "Tim Robbins",
    "id": 1
  },
  {
    "name": "The Godfather",
    "outline": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "rating": 9.2,
    "director": "Francis Ford Coppola",
    "year": 1972,
    "stars": [
      "Marlon Brando",
      "Al Pacino",
      "James Caan"
    ],
    "runtime": 175,
    "genre": [
      "Crime",
      "Drama"
    ],
    "certificate": "R",
    "date": "1974-07-12T10:29:29+05:30",
    "actor": "Marlon Brando",
    "id": 2
  },...]

and I just want to return a new collection with keys name, rating and year... 

How can I achieve this? I have tried only but it returns an empty array. The resulting output should be an array of object not just the values, so "pluck" is not viable in this case.

Can you please help?

Thank you so much!

**Comment by ecrmnn** [comment]
I've tried to get this added to Laravel Collection for years actually.
But unfortunately it's been rejected every time.

The solution is to use `map`.

See example on Runkit; 
https://runkit.com/ecrmnn/64836b9325c5170008f6f3d0

```js
collect(movies).map(({ name, rating, year }) => ({ name, rating, year }));
```

**Comment by jjjrmy** [comment]
mapWithKey?
