### ISSUE TITLE
Cast object to array

### ISSUE THREAD

**Issue by jameslkingsley** [ecrmnn/collect.js#7]
Would it be possible to auto-cast the collection to an array like Laravel does when PHP expects an array? For example this isn't possible right now:

```js
const collection = collect([1,2,3,4,5]);

for (let item of collection) {
    // Do something with item
}
```

**Comment by ecrmnn** [comment]
Great suggestion @jameslkingsley!

I've implemented ``[Symbol.iterator]`` on the ``Collection`` object, so this should be possible now.

**Comment by marlazinger200** [comment]
1
