### ISSUE TITLE
random() mutates the collection

### ISSUE THREAD

**Issue by blx** [ecrmnn/collect.js#89]
> The random method returns a random item from the collection:

Not only that, it shuffles the collection in place:
```js
const a = collect([1, 2, 3, 4, 5])

console.log(a.random())    // 4
console.log(a.all())       // [3, 5, 1, 4, 2]
```

I humbly suggest it would be more clear to either update the documentation to note that, or to adjust the code to be pure -- a user might not expect their ordered array to be shuffled when asking for a random element.

**Comment by mrholeechit** [comment]
There's a PR open to fix this issue #93
